### ISSUE TITLE
Sağ tıklayıp seçtiğim kırmızı noktalar. Yeni oyun başlayınca kaybolmuyor.

### ISSUE THREAD

**Issue by skecer** [RedXBeard/kivy-mines#1]
![screen shot 2015-02-06 at 10 53 59](https://cloud.githubusercontent.com/assets/530552/6076655/33450bd0-adef-11e4-9b8b-458cd39ecf4d.png)

**Comment by RedXBeard** [comment]
thanks, will be fixed.

**Comment by RedXBeard** [comment]
request on
https://github.com/RedXBeard/kivy-mines/pull/2
